### ISSUE TITLE
Accidentals not working?

### ISSUE THREAD

**Issue by kubukoz** [pauliamgiant/sounds-of-scala#24]
Hi! I'm trying to get started with SoS. I've published a local snapshot and I'm doing this:

```scala
package example

import cats.effect.unsafe.implicits.global
import org.scalajs.dom
import org.scalajs.dom.document
import org.scalajs.dom.AudioContext
import org.soundsofscala.models.*
import org.soundsofscala.syntax.all.*
import org.soundsofscala.transport.Sequencer
import org.soundsofscala.Instruments.*
@main
def helloWorld(): Unit = {
  val quickTestSong = G3 + A3.flat + G3

  dom.document.addEventListener(
    "click",
    _ => {

      given audioContext: AudioContext = new AudioContext()

      given ScalaSynth = ScalaSynth()

      val sequencer = Sequencer()

      val song = Song(
        title = Title("Test Song"),
        tempo = Tempo(120),
        swing = Swing.Straight,
        mixer = Mixer(
          Track(
            title = Title("Test Track"),
            musicalEvent = quickTestSong,
            instrument = given_ScalaSynth,
          )
        ),
      )

      sequencer
        .playSong(
          song
        )
        .unsafeRunAndForget()
    },
  )
}

```

It's playing on click, but the accidentals don't seem to have an effect - I hear an A3 regardless of whether I do a `flat` or a `sharp` or nothing. Is there something I'm doing wrong?

**Comment by kubukoz** [comment]
ah, I've dug into the internals and it appears that the octave/accidental aren't taken account in the frequency calculation in `Pitch`. I've hacked something that works, but it's... well, hacky - I'll see if I can get it to a relatively clean state.

**Comment by pauliamgiant** [comment]
Ok great.. firstly here is a PR to rectify that:
https://github.com/pauliamgiant/sounds-of-scala/pull/25
Secondly, I'll update the milestones and docs this week 15 Apr 2024 to make it more explicit where we are at with the libraries functionality as ultimately it is still under construction.

**Comment by paulclearscore** [comment]
This is now implemented @kubukoz
